### ISSUE TITLE
UI breaks if model_range is missing

### ISSUE THREAD

**Issue by davidkopp** [Boavizta/datavizta#73]
There are cloud instances that doesn't include the property `model_range`. If that's the case it leads to the following error:

```plain
Uncaught (in promise) TypeError: S[2].verbose['CPU-1'].model_range is undefined
```

If this error occurs it is not possible to select a different instance type. A refresh of the whole page is required.

Here are some example cloud instance types (aws) that are missing the property `model_range`:
`c7a.large`, `f1.2xlarge`, `h1.2xlarge`, `i3.2xlarge`, `m1.large`, `m7a.large`, `p2xlarge`, `r4.large`, `r7a.large`, `t2.micro`

Expected:
It should not be a problem for the UI if this property is missing. The value of `model_range` should not be considered mandatory.

**Comment by guillaumew** [comment]
Same here. Any t2 instance will have a JS error.
> 3.fa68aaff.js:1 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'value')
    at Object.p (3.fa68aaff.js:1:5935)
    at Object.p (3.fa68aaff.js:1:3532)
    at ae (index.a5442443.js:1:9009)
    at Object.p (3.fa68aaff.js:1:11004)
    at At (index.a5442443.js:1:7935)
    at F (index.a5442443.js:1:7621)

**Comment by da-ekchajzer** [comment]
#74 should fix it. We'll deploy the update soon.
